### ISSUE TITLE
Start an FAQ

### ISSUE THREAD

**Issue by JustAPerson** [cogciprocate/ocl#101]
Perhaps a wiki page or markdown document with some common issues would be a nice addition? For example, [I just found that the Mac OSX driver will not recognize a kernel with no arguments](https://github.com/nengo/nengo_ocl/issues/51#issuecomment-28246773), which seems like an innocent place to begin experimenting.

**Comment by c0gent** [comment]
I've been planning to create a usage guide with an FAQ for about a year now. I need a few clones of myself to get all of the things done that I want :)

As for documenting platform-specific quirks, I'm not sure that there are enough electrons in the universe to track them all...

**Comment by JustAPerson** [comment]
Well perhaps others will find this issue and can list some things here until an FAQ is made :) You're right that there's a lot of platform specific quirks sadly.

If there are any concrete tasks you'd like help with in the code base, I'd be happy to try helping out. I'm using `ocl` for a class project so I'll be investing quite a bit of effort in it.

Best wishes!

**Comment by c0gent** [comment]
Just keep your eye out for unclear documentation or anything confusing and create an issue for it :)

Documentation, as usual, is what's needed most.

I'll create a platform specific quirks page on the wiki and I guess we can just add them there. I'm not sure that people are going to tend to look there though since googling is going to return better/more results 99% of the time.

**Comment by c0gent** [comment]
Going to close this for now. I'm not sure I have a clear idea of what the FAQ should contain, or if it's necessary. There really aren't any questions asked here, let alone any frequent ones.

We can revisit this in the future if needed.
