### ISSUE TITLE
impl Clone for Kernel

### ISSUE THREAD

**Issue by rubdos** [cogciprocate/ocl#111]
First a question: what is the expected behaviour of `Kernel.clone()`?

Then; currently it's `unimplemented!()`, I just wanted to use it... :-)

**Comment by c0gent** [comment]
I'm not sure how that managed to slip by me... Kernels are not allowed to be cloned since the addition of [`KernelBuilder`](https://docs.rs/ocl/0.18.0/ocl/builders/struct.KernelBuilder.html) (for thread safety reasons). To make identical (but separate) kernels re-use [KernelBuilder::build](https://docs.rs/ocl/0.18.0/ocl/builders/struct.KernelBuilder.html#method.build) as many times as needed. `KernelBuilder` can also be cloned.

Thanks for catching this.

**Comment by c0gent** [comment]
25c4de59fdd22909c7e0e15340ea9ef2394e8f2c removes `::clone`.

**Comment by rubdos** [comment]
> To make identical (but separate) kernels re-use KernelBuilder::build as many times as needed. KernelBuilder can also be cloned.

Thank you, that makes sense!
