### ISSUE TITLE
Why are Kernel::enq and KernelCmd::enq unsafe?

### ISSUE THREAD

**Issue by calebwin** [cogciprocate/ocl#147]
The change log says, "`Kernel::enq` and `KernelCmd::enq` are now unsafe functions. Even though the API call itself is safe, all kernel code is inherently untrusted and potentially dangerous."

Can someone elaborate? What exactly makes this call unsafe?

I understand that calling these functions run kernel code on a GPU using data that has been already transferred to there. Is the unsafety because the kernel might fail? What kind of failiure constitutes unsafety? Is the unsafety then just because sometimes the code might fail and crash the whole program?

**Comment by c0gent** [comment]
Unsafety is essentially accessing data you didn't intend to. Memory that may contain overwritten data or memory that is outside of some boundary.

Technically speaking, unsafety applies to GPU memory but keep in mind that OpenCL kernels can and often do run on host memory as well. Since you can do anything you want within a kernel, there is no way to guarantee its memory access is safe and therefore each time you enqueue a kernel there is a chance for unsafe behavior. 

Making the `::enq` methods unsafe is simply the correct/conventional way to indicate that, unlike all other (safe) calls, these functions will do unsafe things and possibly crash if your kernel code has bugs, etc.

**Comment by calebwin** [comment]
OK. Then what would have to be done to make them safe?

If the kernel function is verified to satisfy some sort of specification, is the `::enq` method safe? If so, what requirements would that spec contain?

**Comment by c0gent** [comment]
This would be a massive undertaking. You could either create a memory safety analysis tool for OpenCL C/C++/SPIR-V or create a special dialect of Rust which compiled into SPIR-V.

There has been some [Rust -> SPIR-V work done](https://github.com/MaikKlein/rlsl) but it was not completed and it didn't feature safety checks anyway afaik.

**Comment by c0gent** [comment]
Closing but feel free to reply if you have anything else to add :)
