### ISSUE TITLE
Why not unwrapping Mem dropping ?

### ISSUE THREAD

**Issue by Kerosene2000** [cogciprocate/ocl#32]
https://github.com/cogciprocate/ocl/blob/master/src/core/types/abs.rs#L344

`.ok()` method doesn't panic in any case, but is it important ?

**Comment by c0gent** [comment]
Yes, it should be unwrap. Not sure why I did that.

**Comment by Kerosene2000** [comment]
You do it or you want a PR ?

**Comment by c0gent** [comment]
I'll do it Monday. Not home now.

**Comment by c0gent** [comment]
Alright I remember why I did that now.

I didn't want a possibility for the stack to unwind when releasing objects. If I remember correctly there were problems on certain platforms when releasing (calling `clRelease[...]`) which were causing errors (processed by `errcode_try`). Usually these errors were frivolous and of no importance. I didn't want the potential for a panic every time a user closed an application.

I should have documented my reasoning because I can't remember the details. What needs to happen is to find out exactly in which cases on which platforms errors are returned by a call to any release function and to make sure that the error handling can account for those unusual cases.

It's difficult to know exactly how best to handle all of these platform-specific behaviors without creating a bunch of extraneous (and difficult to maintain) code.

I'd be happy to know if you have any ideas or suggestions on the matter.

**Comment by Kerosene2000** [comment]
Ok, you're right !

The problem is that `drop()` doesn't return a `Result` then the user cannot choose to ignore the error and that's our problem (internally).
The best solution is to log (https://crates.io/crates/log) the error, and let the user do what he want with it !

**Comment by c0gent** [comment]
Well the `.ok()` is there just to suppress the warning.

I haven't really wanted to do any kind of logging because I don't really feel it's appropriate for a crate which is actually fairly low level. I also don't think it's going to be very helpful to a user to give them some sort of arcane low level message straight from the driver.

I think the best way is just to create a separate error handling function, or build some extra logic into the `core::release[...]` calls to selectively ignore unimportant errors.

I'll mess around with this sometime this week when I work on splitting up the crate and some other stuff I've been meaning to do.

**Comment by Kerosene2000** [comment]
why not using:`let _ = ...;` ?

Ok, I think the selection of important/useless errors are not our job, the user as to choose itself... that can be added to the API.

**Comment by c0gent** [comment]
> Ok, I think the selection of important/useless errors are not our job, the user as to choose itself... that can be added to the API.

I completely agree with you in general however it is the job of this library to act as a diplomat for any and all interaction between the user and the OpenCL API, errors included. It would be a dereliction of this duty to allow non-compliant API implementations (ahem, NVIDIA) to suddenly cause the user to have to respond to unusual errors of this kind. It's this library's job to buffer as much quirky stuff as possible without bothering the user unless there's actually something they can do about it.

**Comment by c0gent** [comment]
Here's my solution for now (commited to new ocl-core repo):

https://github.com/cogciprocate/ocl-core/commit/6bf323ca81bbb912ccaa29b41b9a90c85b576c2f

**Comment by Kerosene2000** [comment]
I am ok with your vision of sending to the void useless errors, I didn't encounter this kind of errors for the moment.

WoooWowow ! Are you sure about your `unwrap()` on the `release` compiled program ??
I think maybe in reverse but why permitting a `release` program to `panic!` ?
This is not really the good thing to do, when you check errors on your program this in the `debug` mode (I read about your panic in panic but I didn't agree).

**Comment by c0gent** [comment]
> By the way I love the new splited crates :smile:

Yea I'm glad someone finally got me to finish that. I like it too.

> WoooWowow ! Are you sure about your unwrap() on the release compiled program ??

Yes and the reason is because if there is an error when releasing during drop, the only way to handle the error is to unwind the stack. This ensures that in a release configuration, there are no **silent** errors which may cause data corruption. I want the program to crash before it allows data corruption or mysterious problems which would be extremely hard to trace.

I have this behavior disabled in debug mode because whenever anything causes a panic, it almost always causes an error during drop when the stack is unwinding, making finding the source of the original problem much harder to find. 

I agree this is not ideal but I'm going to leave it this way until we approach 1.0. I will change it before then to .unwrap() in both cases once everything is good and stable and debugging is not an issue (we're probably already at that point honestly).

**Comment by Kerosene2000** [comment]
Fine, the `.ok()` on debug doesn't satisfy me, we will wait the `1.0 release`, like you say, to `.unwrap()` in both cases.

**Comment by c0gent** [comment]
Let me finish crate separation and OpenGL interop then I'll change it.

**Comment by Kerosene2000** [comment]
OpenGl interop doesn't works already ? I work on this no ? 😄 

So cute 😸

**Comment by c0gent** [comment]
Yes it works great but it's not finished yet. I have a bit more to add.

**Comment by c0gent** [comment]
Haven't finished the gl stuff I wanted to do yet but the unwraps have arrived!

cogciprocate/ocl-core@6bf323c
