### ISSUE TITLE
More Dimensions

### ISSUE THREAD

**Issue by Binero** [cogciprocate/ocl#53]
I noticed that [SpatialDims](http://doc.cogciprocate.com/ocl/ocl/enum.SpatialDims.html) only goes up to 3 dimensions. Is this a limitation in OpenCL or in these specific bindings? Could this be extended to 4?

**Comment by c0gent** [comment]
It is not so much an OpenCL limitation as it is a device/platform specific limitation. It just happens to be the convention (largely due to 3d graphics) that virtually every device imposes a three dimensional maximum work item size (this can be queried with [`clGetDeviceInfo`](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/clGetDeviceInfo.html) aka. [`Device::info()`](https://docs.rs/ocl/0.11.0/ocl/struct.Device.html#method.info) but I've never seen anything other than three).

Just because the hardware only supports three work item dimensions, however, shouldn't stop you from using as many as you want. Simply further subdivide your work item and buffer by as many extra divisions as you please. It's exactly the same thing you'd do when using a multi-dimensional array. I routinely use 7 or 8 dimensions on certain complex recursive structures but the sky's the limit. Simply pass the additional dimensions as parameters to kernels and use loops to iterate recursively into them, or however else you'd like to use them. It takes a bit more work and care to set up buffers and keep everything straight within the kernels but it is equivalent to using the built-in dimensions (just without the comforts).

Sorry to take so long to get back to you. Please let me know you need more info or an example of what I mean.

**Comment by Binero** [comment]
I see. I'll use a one dimensional work set then, as recommended. Thanks!

**Comment by c0gent** [comment]
You can still use the three built-in in addition to any extra ones you might use yourself if you want.

**Comment by Binero** [comment]
@c0gent Is there any performance reasons I'd use 3D with one dimension split in two over just 1D split in 4?

**Comment by c0gent** [comment]
Fundamentally there is no inherent difference but it *could* be easier for you to reason about and therefore optimize depending on how you lay out and access the data. Basically the built-in dimensions can be a huge convenience and time-saver.

OpenCL kernels generally perform best when they can access data in workgroup-sized contiguous chunks. Always keep this in mind when deciding how to lay out and access data. This is a big topic so I'll just point you towards the two best guides I know:

https://developer.apple.com/library/content/documentation/Performance/Conceptual/OpenCL_MacProgGuide/TuningPerformanceOntheGPU/TuningPerformanceOntheGPU.html

http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/opencl-optimization-guide/
