### ISSUE TITLE
Should Kernel implement Clone?

### ISSUE THREAD

**Issue by TyOverby** [cogciprocate/ocl#55]
The docs for Kernel say "Reference counter now managed automatically", but as far as I can tell, Kernel doesn't implement clone, so there's no way to make use of this.

btw, I'm in love with this library.  I likely wouldn't have learned opencl if it weren't for this crate!

**Comment by c0gent** [comment]
This is the actual kernel pointer at the heart of `Kernel`:

[ocl-core::Kernel](https://github.com/cogciprocate/ocl-core/blob/master/src/types/abs.rs#L575)

It has a separate type because there are actually three layers to this library, providing users access to lower level interfaces with OpenCL. The [ocl-core documentation](http://doc.cogciprocate.com/ocl_core/ocl_core/) provides a little bit of an explaination of this.

Glad to hear you're enjoying the library. Let me know if you think of any way we can improve it or if you have any other questions. :)

**Comment by c0gent** [comment]
Also, if you're interested, if you read to the bottom of the [trivial example](https://github.com/cogciprocate/ocl/blob/master/examples/trivial.rs) partially shown in the readme you'll see an example of how using ocl-core differs from ocl.

**Comment by TyOverby** [comment]
I understand the layering of ocl/ocl-core/cl-sys, but what I don't get is why `ocl::Kernel` doesn't implement `Clone`.  I'd like to stay in the highest level of abstraction as much as possible and right now the biggest perf hit in my application is from not being able to cache instances of `ocl::Kernel`.

**Comment by TyOverby** [comment]
If Clone is impossible to implement for some reason, maybe `into_raw` and `from_raw` methods so I could cache the `ocl-core::Kernel` instances?

**Comment by c0gent** [comment]
I apologize. I overlooked the main point of your question. 

I've gone ahead and implemented it for now. 583e67314d401487556ca59eb326a5ee6d4234c2.

In thinking back about my reasoning for not deriving it originally, I can remember I was concerned with different instances of the surface `ocl::Kernel` becoming out of sync with the `core::Kernel`.

Please test this out and see if you discover any problems. Leave this issue open and I'll get back to it later in the week.

**Comment by c0gent** [comment]
After letting this rattle around for a minute, I'm curious to know more about your use case. How are you caching them and why?

**Comment by TyOverby** [comment]
I have a workload where I'm dynamically generating opencl programs at runtime and I use those to execute on my data.  Because of the nature of my system, often-times, these dynamically generated programs are exactly the same, so I'd like to reuse them if possible.

Right now I'm caching `Program` objects and calling `Kernel::new` (reusing the cached `Program` instance).  You can see my code [here](https://github.com/TyOverby/implicit-gpu/blob/master/src/opencl/mod.rs#L61).  The first block is where I check to see if I've already compiled a similar program, and if so, I get the kernel out of it.

My current implementation would be fine, but `Kernel::new` is showing up on my profiler, so I figured taking it out would be the easiest resolution.

**Comment by c0gent** [comment]
Interesting.

My intuition is that there must be some way for you to store all of your kernels within a `HashMap` or some other appropriate structure then make a decision about whether or not you need to dynamically create one based on whether or not your structure does not already contain it.

Even that however doesn't sit right with me. There must be some way to design the kernels in such a way that they can all be created upon startup and simply selected during runtime. Surely you can design the kernels in such a way that parameters can be changed as necessary between calls to suit the situation. Perhaps some rethinking about your overall design may be in order. Let me know if I'm way off base here.

Barring that, the most lightweight way to clone and store many identical kernels would be to initially create and configure an `ocl::Kernel`, then clone its core using `::core_as_ref().clone()`. You would then call `ocl_core::enqueue_kernel(...)` directly. That way you're only storing a single pointer whose reference count is managed by the OpenCL runtime.

You could of course alternatively wrap your `ocl::Kernel` in an `Rc<RefCell<...>>` or some other Rust reference counted pointer.

Let me know what you figure out :)

**Comment by TyOverby** [comment]
> @c0gent
>My intuition is that there must be some way for you to store all of your kernels within a HashMap or some other appropriate structure then make a decision about whether or not you need to dynamically create one based on whether or not your structure does not already contain it.

Yeah, this is exactly what I want!  However, not being able to `clone` them out of the hashmap for `enq`ing is what's holding me up.

> @c0gent
> Surely you can design the kernels in such a way that parameters can be changed as necessary between calls to suit the situation. 

Parameters to the Kernel can be changed for sure, but it's the function `core:: create_kernel` that's eating my time budget.

> @c0gent
> Barring that, the most lightweight way to clone and store many identical kernels would be to initially create and configure an ocl::Kernel, then clone its core using ::core_as_ref().clone(). You would then call ocl_core::enqueue_kernel(...) directly. That way you're only storing a single pointer whose reference count is managed by the OpenCL runtime.

This sounds close to the way that I suggested up above:

> @tyoverby
> If Clone is impossible to implement for some reason, maybe into_raw and from_raw methods so I could cache the ocl-core::Kernel instances?

I'd rather keep using the higher level `ocl` library as much as possible.

> @c0gent 
> You could of course alternatively wrap your `ocl::Kernel` in an `Rc<RefCell<...>>` or some other Rust reference counted pointer.

Is this true?  All of `ocl::Kernel`s methods take `self` by value.  I don't think this would work inside of an `Rc` (or `Arc`).

**Comment by c0gent** [comment]
> ... not being able to clone them out of the hashmap for enqing is what's holding me up.

Why would you need to clone them out of the hashmap for enqueuing?

> ...  it's the function core:: create_kernel that's eating my time budget.

I'm still not sure why you can't create all necessary kernels just once, upon startup. Perhaps this is related to the point above.

> All of ocl::Kernels methods take self by value. I don't think this would work inside of an Rc (or Arc)

Many ocl::Kernel methods take `self` by value during creation but each of those methods also has `&self` counterparts. That doesn't matter though because you can create each kernel and setup up work sizes and arguments before wrapping in a `RefCell` etc. 

All you really will ever need to use during the running of your application once the kernels are already created will be one of the `::set_arg_...` methods, [`::enq`](https://docs.rs/ocl/0.11.0/ocl/struct.Kernel.html#method.enq), or [`::cmd`](https://docs.rs/ocl/0.11.0/ocl/struct.Kernel.html#method.cmd). All you need to use those is a mutable (in the case of `::set_arg_...`) or immutable (`::enq`, `::cmd`) reference. `Kernel` can be stored in a HashMap, a Vec, a RefCell/RefMut/Mutex or anything else and used without having to clone it first.

The only exception to that, I suppose, is the worksize methods (`::gwo`, `::gws`, `::lws`). I never considered that worksizes might be need to be altered after kernel creation but indeed I can see where that might be useful. Is a method to alter those parameters after creation what's needed here?

**Comment by TyOverby** [comment]
I must be missing something in the design of `ocl::Kernel`.  The way I've been using it is by taking a Kernel, using it, and then throwing it away.  If what I'm understanding from you is correct, I can create an `ocl::Kernel`, fill it with arguments and parameters, use it, clear it, and then store it away to be used again. 


> @c0gent 
>I'm still not sure why you can't create all necessary kernels just once, upon startup. Perhaps this is related to the point above.  

I can't create "all the necessary kernels" because I don't know which ones will be used, and how many times they'll be called.

**Comment by TyOverby** [comment]
I guess the bit that confused me is that in `ocl` a "Kernel" represents two things: 

1. A pointer to a specific function in a compiled `Program`.
2. A collection of properties and arguments to be applied to the Kernel when it is called.

Are these two concepts the same in raw OpenCL?

Maybe I should just switch to using `ocl_core` for this bit.

**Comment by c0gent** [comment]
Yes, a kernel does represent both of those two things.

Each `Kernel` (`cl_kernel`/`ocl_core::Kernel`/`ocl::Kernel`) represents a pre-configured instance of a specific `__kernel` within a `Program`. Optimally, you only need to create them once, upon program startup, then re-use them throughout the life of your program.

Now, two situations may arise if the parameters of your kernel need changing:

If you want to save the configuration (arguments/worksizes) of multiple instances of a kernel and refer back to them later, i.e. you will be reusing the exact same configurations again, then simply store them in your preferred 'cache' data structure and use them over and over. 

If however, you'll have a situation where the parameters may change wildly and there are a huge number of possible combinations of parameters, creating a new `Kernel` would be impractical or useless because you probably won't need that exact same one later again. In this case, create a single kernel upon program startup, then before enqueuing that kernel when the time comes, change the necessary parameters, call `::cmd` to set up the work sizes, and enqueue. Rinse and repeat using the same `Kernel`. The only reason you even need to create a new kernel at all is if you want to save the parameter/worksizes setup for later use, simply as a convenience (and performance increase in some cases). As I mentioned, if the number of possible combinations is too large, doing this becomes silly at a certain point.

Kernels are not meant to be created constantly, they're generally meant to be created once or just a small handful of times. If you need advice or examples of how to structure your program to accommodate this design don't hesitate to ask.

As far as `ocl_core` is concerned, If you're programming in idiomatic Rust, you don't need to use it directly but there's no harm if you do. There are certain situations where it may make things more convenient but for the most part, storing a bunch of core pointers instead of passing around references is an indication that your design could be improved.

**Comment by c0gent** [comment]
@TyOverby 

How are things coming? Let me know if you need any help with your design. I'm always available to give out bad advice :)

**Comment by c0gent** [comment]
Closing this issue. Reply here or create a new issue if you have any questions or need help.

**Comment by c0gent** [comment]
@TyOverby 

Thought you might like to know in case you still need this: `Kernel` will now implement `Clone` again in the next version of ocl. It's still recommended to share references (`&` or `Ref`) whenever possible but the option to clone them is there (though they can no longer be passed between threads).

Set your dependency to the master branch if you want to try these changes out early (warning: lots of breaking changes).

Let me know how your project is coming along.

**Comment by TyOverby** [comment]
Thanks @c0gent!  Project has been stalled for a while, but when I get back to it, this'll be the first thing I change!
