### ISSUE TITLE
No Cargo Release Since Breaking API Change

### ISSUE THREAD

**Issue by cathalgarvey** [cogciprocate/ocl#57]
Hi, looks like since the [breaking change][brchng] a few months back, there hasn't been a version bump on Cargo. I discovered this because some examples weren't [running][pr].

The examples with that PR will now point to the base repo, so they work again.. but is it time for a new Cargo push? :)

Thanks!

[brchng]: https://github.com/cogciprocate/ocl/commit/619754932b0faf78fa25ccd245016ec633ebdd04
[pr]: https://github.com/cogciprocate/ocl/pull/56

**Comment by c0gent** [comment]
Looks great, thanks for catching that. I considered locking the ocl version for those examples but because they also serve as regression tests I wanted them to always use the latest Ocl version. I think your solution serves both purposes, I hadn't even considered it.

I'll go ahead and bump the Cargo version as well.

Thanks :)
