### ISSUE TITLE
Profiling events on Mac OS X

### ISSUE THREAD

**Issue by michael-p** [cogciprocate/ocl#66]
`get_event_profiling_info` in `ocl-core` currently returns an OpenCL error on OSX. I did some investigation on this and found out that the reason is the [first call](https://github.com/cogciprocate/ocl-core/blob/master/src/functions.rs#L2000) to `ffi::clGetEventProfilingInfo` in `get_event_profiling_info` which is used to determine the size of the requested profiling information. More precisely, the parameter `param_value_size` (third argument) is set to `0 as size_t` here which does not work on OSX (even using the OpenCL C API). Instead, one needs to pass something that is at least as big as the requested information, so in this case any number `>= 8` will do as the returned timestamps are all 64 bits.

I suggest changing that argument from `0 as size_t` to something like `if cfg!(target_os="macos") { size_t::max_value() } else { 0 }`. (could also just use `8` instead of `size_t::max_value()` but in case future OpenCL versions specify new profiling information larger than 8 bytes it would then fail again)

I'm not sure why the behavior here is different than it is on other platforms, probably just a slightly different interpretation of the OpenCL specs by Apple, which says in chapter 5.12:
> param_value_size is used to specify the size in bytes of memory pointed to by param_value. This size must be >= size of return type as described in table 5.19.

**Comment by c0gent** [comment]
(*As I typed this response the cause slowly became clear so it's a bit meandering. I've left it all here anyway.*)

Interesting. Are you on a 64 bit machine? If so then size_t = usize which = 8 bytes in size.

I think I might have some idea what's going on here. You'll notice that the `ocl_core::get_event_profiling_info` function makes two calls to  `clGetEventProfilingInfo`. The first call with a 0 size and null result ptr and is meant simply as a request for the `result_size` ([`param_value_size_ret`](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clGetEventProfilingInfo.html)) so that an appropriate amount of memory can be allocated for the result. This is a typical pattern for C APIs. All other `clGet***Info` functions happily accept 0 (and ignore it) when `*param_value` is null because it is undetermined at the time of that first call to the `clGet***Info` function.

When I first created the `ocl_core::get_event_profiling_info` function I simply copied the basic template from the other get info functions. First determine result size, then get result. Since `clGetEventProfilingInfo` always has a `param_value_size` of `size_of::<size_t>()` (8 bytes on 64 bit platforms) the Apple developers must have just figured no one would do the whole size-request thing and simply made it an error to pass `0` for `param_value_size` even if `*param_value` is null. This is one of those areas where the OpenCL specification is not explicit (and makes chasing down platform specific tasks such a joy).

So... that was an extremely long-winded way of saying that your original suggestion was perfectly right. In an effort to reduce extra platform-specific compilation code though I'll simply pass `size_t::max_value()` for `param_value_size` on every platform since it should be ignored anyway and we'll see how that works.

**Comment by c0gent** [comment]
If you get a chance, please try the latest changes to ocl-core:
```
git clone https://github.com/cogciprocate/ocl-core.git
cd ocl-core
cargo run --example info_core
```
Let me know if the Apple-OpenCL gods are happy with that :)

**Comment by michael-p** [comment]
Works! Nice! :)
One of the tests (`tests::vector_types::test_vector_types`) fails but that's just because it's using `double3` which are not supported on the device. The error message is kinda cute:
```
<program source>:2:61: error: variable has incomplete type 'double3' (aka 'struct __Unsupported_Type__Do_not_use_double3_on_this_device')
        __kernel void add(__global double3* buffer, double3 addend) {
...
```

**Comment by c0gent** [comment]
Haha, ok cool.
