### ISSUE TITLE
Troubleshoot get_gl_context_info_khr

### ISSUE THREAD

**Issue by Nopey** [cogciprocate/ocl#87]
I thought this should have its own issue
## c0gent's debugging notes
from `ocl-core/src/functions.rs`
For some reason, calling the function pointer returned by the call to ffi::clGetExtensionFunctionAddressForPlatform causes a segfault (ffi::clGetExtensionFunctionAddressForPlatform appears to be working just fine). The function pointer returned is not null.

Further investigation into the what address the returned function pointer points to is needed. There may be some Rust-specific quirk having to do with how libraries are loaded into memory. There may alternatively just be a simple mistake somewhere.

**Comment by c0gent** [comment]
To clarify, as the title states the function in question here is [`::get_gl_context_info_khr`](https://github.com/cogciprocate/ocl/blob/76712286991044debf94f5fd9fc87e1d612815fb/ocl-core/src/functions.rs#L800). The function should return the OpenCL device (or devices) associated with a particular OpenGL context.

In order to call [`clGetGLContextInfoKHR`], because it is an extension function (with a `KHR` suffix), it is necessary to first obtain a function pointer to it using [`clGetExtensionFunctionAddressForPlatform`]. This is analogous to loading function pointers for OpenGL, Vulkan, etc.

In my tests, the pointer returned from [`clGetExtensionFunctionAddressForPlatform`] is not null which along with the fact that the extension is definitely supported by my device and platform (and works fine) should mean that the returned pointer is valid. Attempts to call the function using the pointer cause a segfault every time, regardless of the parameters passed. I may very easily be making a mistake somewhere but I've checked everything I can think of. Further eyeballs and testing by others are needed.

Another step would also be to load another function to rule out [`clGetExtensionFunctionAddressForPlatform`] as the culprit. The only other extension functions I'm familiar with are [these DirectX ones](https://www.khronos.org/registry/OpenCL/extensions/khr/cl_khr_d3d10_sharing.txt) and I'm not set up to test them. Perhaps someone familiar with DirectX+OpenCL interop could help. I'm sure there must be [others](https://www.khronos.org/registry/OpenCL/extensions/) as well.

On a side note, @Nopey has designed a clever workaround until we get this function working. It iterates through all GPU devices on each platform and returns the first one that allows a context to be created with the relevant interop properties seems to work. This is hacky and could be brittle, but works as long as the user doesn't have too many graphics capable GPUs (and that they happen to be in just the right order). The code for this is in his new [ocl-interop](https://github.com/cogciprocate/ocl/tree/master/ocl-interop) addition.

[`clGetGLContextInfoKHR`]:
 https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clGetGLContextInfoKHR.html
[`clGetExtensionFunctionAddressForPlatform`]:
 https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clGetExtensionFunctionAddressForPlatform.html
