### ISSUE TITLE
Cloning kernels before arguments are specified.

### ISSUE THREAD

**Issue by jonysy** [cogciprocate/ocl#97]
Hello,

This issue is related to #55. I have a similar use case regarding caching many `kernel` instances once at startup, but I've run into a wall since OCL disallows cloning `kernels` before their arguments have been specified.

Are there any workarounds? And what's the reason for the restriction? (LOC can be found [here](https://github.com/cogciprocate/ocl/blob/4f1a1a9cf82d05cc526f912bf799b77c2d7c7541/ocl/src/standard/kernel.rs#L859))

Kind regards

**Comment by c0gent** [comment]
The short answer is that you may want to use [`ocl_core::Kernel`](https://docs.rs/ocl-core/0.7.0/ocl_core/types/abs/struct.Kernel.html) for your purposes. You will have to use various `ocl_core` functions such as [`create_kernel`](https://docs.rs/ocl-core/0.7.0/ocl_core/fn.create_kernel.html), [`set_kernel_arg`](https://docs.rs/ocl-core/0.7.0/ocl_core/fn.set_kernel_arg.html), and [`enqueue_kernel`](https://docs.rs/ocl-core/0.7.0/ocl_core/fn.enqueue_kernel.html). These functions are equivalent to [clCreateKernel](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clCreateKernel.html), [clSetKernelArg](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clSetKernelArg.html), and [clEnqueueNDRangeKernel](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html). You won't run into any restrictions that way, you'll just have more verbose code and have to be a bit more careful.

The long answer is that because [`Kernel`] offers more features than the bare-bones OpenCL kernel such as checks on argument types and the use of 'named' (string) arguments, allowing a kernel to be cloned before all arguments have been specified requires more internal complexity and potentially more runtime performance cost. 

Because of the shortcoming you've run into (and other API changes that would be nice to make) [`Kernel`] has been on the slate for a redesign for a while. There's a lot more to say about this and if you're interested in discussing more about it or you have any other questions or suggestions please don't hesitate :)

[`Kernel`]: https://docs.rs/ocl/0.16.0/ocl/struct.Kernel.html

**Comment by c0gent** [comment]
A number of changes to `Kernel` have just landed on master. You can now use `KernelBuilder` (returned by `Kernel::builder()`) to create as many identical kernels as you want. `Kernel` cannot be cloned at all now but the `KernelBuilder` can. More details can be found in [`RELEASES.md`](https://github.com/cogciprocate/ocl/blob/master/RELEASES.md). 

If you want to have references to the exact same `Kernel` (not just an identical one) you could also wrap the `Kernel` with an `Arc<Mutex<_>>` or `Rc<RefCell<_>>`, though using the `ocl_core::Kernel` directly, as I mentioned above, is a more efficient option (it already contains a reference counted pointer internally).

Hopefully these changes make things easier for you. Please let me know what you decide and how everything goes :)
